name: mora
version: 1

#accesskey: fuck_world
#cron:
#  - description: cron task run every 45 mins
#      url: cron/every_45_mins.php
#      schedule: */45 * * * *
#      timezone: Beijing

handle:
  # index 居然支持子目录！
  - directoryindex: frontend/index.html index.php index.html

  - errordoc: 404 /404.html

  # 需要密码访问
  - passwdaccess: if(path ~ "/logs.php$") passwd "mora:qiu8310"

  # 对cron任务保护，防止被外部抓取，我们将cron任务放在cron目录下(sae中cron服务执行时，走的是内部网络)
  - hostaccess: if(path ~ "^/cron/") allow "10.0.0.0/8"

  # 重定向
  # Official docs: http://sae.sina.com.cn/doc/php/runtime.html#url
  # http://blog.sina.com.cn/s/blog_622134fd0102uyhp.html

  # ~（正则匹配），~*(正则匹配大小写不敏感)，!~（正则不匹配）
  # ==（相等，用于字符串和数字），!=（不相等，用于字符串和数字），> ，>=， <， <=（比较操作符仅用于整形数字）
  - rewrite: if(!is_dir() && !is_file() && path ~ "^([^\.]*)$") goto "/frontend/index.html"
  - rewrite: if(!is_dir() && !is_file() && path ~ "^(.*)$") goto "/frontend/$1"


  # 设置过期时间
  - expire: if(path ~ "(\.js|\.css|\.png|\.jpe?g|\.gif|\.svg)$") time 864000


  # 压缩
  - compress: if (path ~ "(\.js|\.css|\.png|\.jpe?g|\.gif|\.svg)$" ) compress


