language: node_js
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - 'iojs'
branches:
  only:
    - master

os:
  - linux
  - osx

before_script:
  - 'gem install sass --version "=3.4.5"'
  - 'gem install compass --version "=1.0.1"'
  - 'gem install ceaser-easing --version "=0.7"'
  - 'npm install -g bower grunt-cli'
  - 'bower install'

after_script:
  - 'grunt coveralls'

notifications:
  email:
    - 710067681@qq.com
